import { Award, CheckCircle2, CircleAlert, GraduationCap, TrendingUp } from 'lucide-react'
import { getPredictionStatus, getScoreState } from '../utils/predictionUtils'

export default function PredictionResult({ result }) {
  const score = Number(result.predicted_score)
  const state = getScoreState(score)
  const status = getPredictionStatus(score)
  const gaugeStyle = { background: `conic-gradient(${state.color} ${score * 3.6}deg, #e8edf3 0deg)` }
  return <section className="card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><p className="eyebrow">Prediction result</p><h2 className="mt-1 text-lg font-semibold text-ink">Your model-generated estimate</h2></div><div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[180px_1fr]"><div className="mx-auto grid h-40 w-40 place-items-center rounded-full p-2" style={gaugeStyle} aria-label={`Predicted score ${score.toFixed(1)} out of 100`}><div className="grid h-full w-full place-items-center rounded-full bg-white text-center"><span className="text-3xl font-semibold tracking-tight text-ink">{score.toFixed(1)}</span><span className="text-xs font-medium text-slate-500">out of 100</span></div></div><div><div className="grid grid-cols-2 gap-3"><ResultMetric icon={Award} label="Grade" value={result.grade} /><ResultMetric icon={TrendingUp} label="Performance" value={result.performance} /></div><div className="mt-4 flex items-center gap-3 rounded-xl border px-4 py-3 text-sm" style={{ borderColor: `${state.color}33`, backgroundColor: `${state.color}0d` }}><span className="grid h-8 w-8 place-items-center rounded-lg text-white" style={{ backgroundColor: state.color }}>{status === 'Pass' ? <CheckCircle2 size={17} /> : <CircleAlert size={17} />}</span><div><p className="font-semibold text-ink">Prediction Status: {status}</p><p className="mt-0.5 text-xs text-slate-600">Visual score category: {state.label}</p></div></div></div></div><div className="border-t border-slate-100 bg-slate-50/70 px-5 py-4 sm:px-6"><div className="flex gap-3"><GraduationCap className="mt-0.5 shrink-0 text-brand-600" size={18} /><div><h3 className="text-sm font-semibold text-ink">Performance Summary</h3><p className="mt-1 text-sm leading-6 text-slate-600">The API returned a predicted score of <strong>{score.toFixed(1)}</strong>, grade <strong>{result.grade}</strong>, and performance classification <strong>{result.performance}</strong>. Status is calculated on the frontend using a 40/100 pass threshold.</p></div></div></div></section>
}

function ResultMetric({ icon: Icon, label, value }) {
  return <div className="rounded-xl border border-slate-100 bg-white p-3.5"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><Icon size={15} className="text-brand-600" />{label}</div><p className="mt-2 text-lg font-semibold text-ink">{value}</p></div>
}
