import { ArrowRight, BarChart3, BrainCircuit, GraduationCap, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

const benefits = [{ icon: GraduationCap, title: 'Student Performance', text: 'Bring study habits and academic context into one simple input flow.' }, { icon: BrainCircuit, title: 'ML Prediction', text: 'Submit data to the existing machine learning prediction API.' }, { icon: BarChart3, title: 'Academic Insights', text: 'Review your submitted factors and returned prediction in a clear dashboard.' }]

export default function Home() {
  return <><section className="relative overflow-hidden border-b border-slate-200 bg-white"><div className="hero-orb absolute right-[-9rem] top-[-12rem] h-[31rem] w-[31rem] rounded-full" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:py-24 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-brand-100 bg-brand-50 px-3 py-1.5 text-xs font-semibold text-brand-700"><Sparkles size={14} />Powered by Machine Learning</div><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-0.04em] text-ink sm:text-5xl lg:text-6xl">Predict Student Performance with Machine Learning</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Analyze study habits, attendance, previous scores, sleep and tutoring sessions to estimate academic performance.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/predict" className="button-primary justify-center">Predict Student Score <ArrowRight size={18} /></Link><Link to="/about" className="button-secondary justify-center">Learn More</Link></div></div><HeroPanel /></div></section><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="max-w-xl"><p className="eyebrow">Purpose-built clarity</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-ink">A focused view of the inputs that matter.</h2></div><div className="mt-9 grid gap-4 md:grid-cols-3">{benefits.map(({ icon: Icon, title, text }) => <article key={title} className="card p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Icon size={20} /></span><h3 className="mt-5 font-semibold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section></>
}

function HeroPanel() { return <div className="card mx-auto max-w-md p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-ink">Student Performance</p><p className="mt-1 text-xs text-slate-500">Prediction workspace</p></div><span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Ready</span></div><div className="mt-7 rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-wider text-slate-500">Model estimate</p><p className="mt-1 text-3xl font-semibold tracking-tight text-ink">Score <span className="text-lg text-slate-400">/ 100</span></p></div><div className="grid h-14 w-14 place-items-center rounded-full border-[7px] border-brand-500 text-xs font-semibold text-brand-700">ML</div></div></div><div className="mt-5 grid grid-cols-3 gap-3">{['Study habits', 'Attendance', 'Support'].map((item) => <div key={item} className="rounded-lg border border-slate-100 p-3 text-center text-xs font-medium text-slate-600">{item}</div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Enter current student factors to request a result from the connected prediction service.</p></div> }
